name: SAnnounce
author: solo
version: 1.0.0
main: solo\sannounce\SAnnounce
api: [3.0.0, 3.1.0, 4.0.0]
permissions:
  sannounce:
    default: op
    children:
      sannounce.command:
        default: op
        children:
          sannounce.command.add:
            default: op
          sannounce.command.list:
            default: true
          sannounce.command.remove:
            default: op
          sannounce.command.setinterval:
            default: op
          sannounce.command.setprefix:
            default: op
